# [Choice] .NET version: 7.0, 6.0, 5.0, 3.1, 6.0-bullseye, 5.0-bullseye, 3.1-bullseye, 6.0-focal, 5.0-focal, 3.1-focal
ARG VARIANT="8.0"
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/vscode/devcontainers/dotnet:${VARIANT}

